# unsplash categories
UNSPLASH_CATEGORIES: [ 'wallpapers','3d-renders','travel','nature','street-photography','experimental','textures-patterns',
                       'animals','architecture-interior','fashion-beauty','film','food-drink','people','spirituality',
                       'business-work','athletics','health','arts-culture' ]

BBC_CATEGORIES: ['technology','business','politics','science_and_environment','health','education','entertainment_and_arts']


CLIP_MODEL: ['openai/clip-vit-base-patch32']

MORE_INFO: { 'zero_shot_classification_imagery': "Because CLIP was trained on a diverse set of images and paired natural language 
            descriptions, CLIP is able to generalize its understanding to new and unseen data and correctly classify both 
            objective features *in the image* but also more abstract concepts *related to the image*. \n\nFeel free to experiment with more abstract concepts as 
            well as more obvious objective image features with this app",
            'zero_shot_classification_text': "Because CLIP was trained on a diverse set of images and paired natural language 
             descriptions, CLIP is able to generalize its understanding to new and unseen data and correctly classify both 
             objective features but also more abstract concepts.",
            'semantic_search': "Semantic search is a search technique that aims to understand the meaning and context of 
            words and phrases in a search query rather than just returning results that are aligned with keywords.\n\n 
            CLIP enables a more intuitive and natural way of searching for images based on their content. One way of 
            achieving this is by calculating the cosine similarity between input embeddings (search query) and target 
            embeddings (images/other text) ",
            'clustering': "We can use CLIP's encoder to extract text and image embeddings from any input data source. 
            Embeddings are mathematical representations of the input data. Amongst other things, these embeddings can 
            be used to cluster similar items. By incorporating dimensionality reduction techniques such as UMAP, 
            clusters can be visualised and interrogated. \n\nBe patient with this app, sometimes it can be slow to generate UMAP projections." }


